#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/submission.py /autograder/source/ &> /dev/null
cp /autograder/submission/submission.py /autograder/source/tests/

cd /autograder/source

python3 run_tests.py > /autograder/results/results.json
